before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo echo "max_prepared_transactions = 100" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database blobstore_jdbc;' -U postgres
  - mysql -e 'create database blobstore_jdbc;'
script: mvn bundle:install -Dpostgresql.enabled=true -Dpostgresql.user=postgres -Dpostgresql.password= -Dmysql.database=blobstore_jdbc -Dmysql.user=travis -Dmysql.password= 
install: true
